//
//  MediaItemsRouter.swift
//  iTunesSearch
//
//  Created by Mohamed Nassar on 29/01/2021.
//  Copyright (c) 2021 Nagarro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MediaItemsRoutingLogic {
  // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol MediaItemsDataPassing {
  var dataStore: MediaItemsDataStore? { get }
}

class MediaItemsRouter: NSObject, MediaItemsRoutingLogic, MediaItemsDataPassing {
  weak var viewController: MediaItemsViewController?
  var dataStore: MediaItemsDataStore?

  // MARK: Routing

  // func routeToSomewhere(segue: UIStoryboardSegue?)
  // {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  // }

  // MARK: Navigation

  // func navigateToSomewhere(source: MediaItemsViewController, destination: SomewhereViewController)
  // {
  //  source.show(destination, sender: nil)
  // }

  // MARK: Passing data

  // func passDataToSomewhere(source: MediaItemsDataStore, destination: inout SomewhereDataStore)
  // {
  //  destination.name = source.name
  // }
}
